# Generated by Django 3.2.6 on 2021-08-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='owner',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
