# Generated by Django 3.2.6 on 2021-08-13 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cards_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNewCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('upload_img', models.FileField(upload_to='uploadImg/')),
                ('description', models.TextField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.category')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insert_code', to='cards.cards')),
            ],
        ),
    ]
