# Generated by Django 3.2.6 on 2021-08-13 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_addnewcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewcode',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insert_code', to='cards.cards'),
        ),
        migrations.AlterField(
            model_name='addnewcode',
            name='upload_img',
            field=models.ImageField(upload_to='uploadImg/'),
        ),
    ]
