# Generated by Django 3.2.6 on 2021-08-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20210813_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='code_blog',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
