# Generated by Django 3.2.6 on 2021-08-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_cards_code_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='categoryPhoto/'),
            preserve_default=False,
        ),
    ]
