# Generated by Django 3.2.6 on 2021-08-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='code_blog',
            field=models.TextField(max_length=5000),
        ),
    ]
